
http:
  address: 0.0.0.0
  port: 8080

mysql:
  path: localhost:3306
  config: charset=utf8&parseTime=True&loc=Local&timeout=10s
  db-name: mall
  username: root
  password: SmallEast1022.
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""